//! Desired instance configuration: the user's editable statement of what an
//! instance *should be*, kept strictly separate from installed state.
//!
//! The configuration owns the Minecraft version, the mod-loader kind and
//! version policy, the memory allocation, additional JVM arguments, and the
//! optional windowed resolution. It never owns anything installation decided:
//! the concrete Aurora release pin, the resolved loader version of an
//! installed instance, and every installed-state manifest stay outside it.
//!
//! ## Memory policy
//!
//! Memory is stored in whole mebibytes and produces exactly one authoritative
//! JVM heap argument (`-Xmx<mib>m`) generated by the launcher. Custom JVM
//! arguments may not carry heap flags (`-Xmx`, `-Xms`, `-Xmn`, their
//! `-XX:`/long-option spellings); a conflict is rejected with an explanation
//! instead of being resolved by silent precedence. Aurora deliberately does
//! not set `-Xms`: letting the JVM grow the heap from its own initial-size
//! heuristic avoids overcommitting host memory, and many launchers set `-Xms`
//! only out of convention.
//!
//! ## JVM argument text
//!
//! Additional JVM arguments persist as the user's raw text and parse into an
//! argument vector at each trust boundary (configuration save and launch
//! assembly) with one documented rule set, modeled on Windows command-line
//! tokenization:
//!
//! - whitespace outside quotes separates tokens;
//! - double quotes group text (spaces inside are preserved); `""` is one
//!   empty token;
//! - a run of backslashes followed by a quote yields half as many literal
//!   backslashes, and the quote is literal when the run is odd (escaped) or
//!   toggles quoting when even;
//! - backslashes not followed by a quote are literal;
//! - an unterminated quote is malformed.
//!
//! Nothing here ever touches a shell: the parsed vector flows straight into
//! the structured process Command API.

use std::fmt;

use serde::{Deserialize, Serialize};

use crate::minecraft::metadata::{InvalidMinecraftVersion, MinecraftVersionId};

/// The launcher-owned default memory allocation: 2048 MiB.
///
/// A deliberately modest, host-independent default in the range modded
/// Minecraft works with; it is a documented product decision, not a fraction
/// of the developer's machine.
pub const DEFAULT_MEMORY_MIB: u32 = 2048;
/// The smallest allocation the launcher accepts (modern Minecraft will not
/// start meaningfully below this).
pub const MIN_MEMORY_MIB: u32 = 512;
/// The largest allocation the launcher accepts — a sanity ceiling, not a
/// hardware probe.
pub const MAX_MEMORY_MIB: u32 = 32_768;

/// Minecraft's own default windowed resolution (854×480), used when the user
/// enables a custom window without values of their own.
pub const DEFAULT_WINDOW_WIDTH: u16 = 854;
pub const DEFAULT_WINDOW_HEIGHT: u16 = 480;
pub const MIN_WINDOW_DIMENSION: u16 = 100;
pub const MAX_WINDOW_DIMENSION: u16 = 7680;

/// Bounds on the parsed custom argument vector.
const MAX_JVM_ARGUMENT_COUNT: usize = 64;
const MAX_JVM_ARGUMENT_LENGTH: usize = 4_096;
const MAX_JVM_ARGUMENTS_TEXT_LENGTH: usize = 8_192;

/// The desired user configuration of one instance: what the user wants it to
/// be, as opposed to what is installed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InstanceConfiguration {
    minecraft_version: String,
    loader: LoaderConfiguration,
    memory_mib: u32,
    /// Raw user text; parsed by [`parse_jvm_arguments`] at every trust
    /// boundary. Empty by default.
    additional_jvm_arguments: String,
    /// Optional windowed resolution; `None` keeps Minecraft's default
    /// behavior (Mojang's `has_custom_resolution` feature stays off).
    window: Option<WindowConfiguration>,
}

/// The mod loader of a desired configuration.
///
/// The model is an explicit kind-plus-policy shape so future loader kinds are
/// additive, but only kinds with a genuinely implemented installation and
/// launch pipeline are representable. Fabric is that kind today; vanilla is
/// deferred because the composed plan, installer, and launch assembly are
/// deliberately Fabric-direct (see ARCHITECTURE.md).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoaderConfiguration {
    kind: LoaderKind,
    policy: LoaderPolicy,
}

/// The kind of mod loader an instance wants.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum LoaderKind {
    Fabric,
}

impl LoaderKind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Fabric => "fabric",
        }
    }
}

impl fmt::Display for LoaderKind {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// How the concrete loader version is chosen when content is installed.
///
/// `Automatic` resolves the newest *stable* loader the official Fabric Meta
/// lists for the configured Minecraft version at install time — an explicit
/// user policy, not a silent substitution of a requested version. The
/// resolved version is then pinned in installed state and never drifts
/// afterward; only a deliberate re-installation re-resolves it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", tag = "type")]
pub enum LoaderPolicy {
    Automatic,
    Pinned { version: String },
}

/// A custom windowed resolution, passed through Minecraft's own
/// `has_custom_resolution` launch-argument feature.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WindowConfiguration {
    width: u16,
    height: u16,
}

impl Default for InstanceConfiguration {
    fn default() -> Self {
        Self {
            minecraft_version: String::new(),
            loader: LoaderConfiguration {
                kind: LoaderKind::Fabric,
                policy: LoaderPolicy::Automatic,
            },
            memory_mib: DEFAULT_MEMORY_MIB,
            additional_jvm_arguments: String::new(),
            window: None,
        }
    }
}

impl InstanceConfiguration {
    /// A default configuration for one exact Minecraft version.
    pub fn for_minecraft_version(version: impl Into<String>) -> Self {
        Self {
            minecraft_version: version.into(),
            ..Self::default()
        }
    }

    /// Builds a full configuration from its command-boundary parts. This is
    /// the one constructor outside deserialization that can name every
    /// field; validation stays the caller's explicit step.
    pub fn from_parts(
        minecraft_version: impl Into<String>,
        loader: LoaderConfiguration,
        memory_mib: u32,
        additional_jvm_arguments: impl Into<String>,
        window: Option<WindowConfiguration>,
    ) -> Self {
        Self {
            minecraft_version: minecraft_version.into(),
            loader,
            memory_mib,
            additional_jvm_arguments: additional_jvm_arguments.into(),
            window,
        }
    }

    /// Derives the migrated configuration for a schema-2 record: the
    /// Minecraft and pinned loader versions of the installed release remain
    /// exactly what the instance had, and the new fields take safe defaults.
    pub fn migrated_from_release_pin(minecraft_version: &str, fabric_loader_version: &str) -> Self {
        Self {
            minecraft_version: minecraft_version.to_owned(),
            loader: LoaderConfiguration {
                kind: LoaderKind::Fabric,
                policy: LoaderPolicy::Pinned {
                    version: fabric_loader_version.to_owned(),
                },
            },
            ..Self::default()
        }
    }

    pub fn minecraft_version(&self) -> &str {
        &self.minecraft_version
    }

    pub fn loader(&self) -> &LoaderConfiguration {
        &self.loader
    }

    pub fn memory_mib(&self) -> u32 {
        self.memory_mib
    }

    pub fn additional_jvm_arguments(&self) -> &str {
        &self.additional_jvm_arguments
    }

    pub fn window(&self) -> Option<WindowConfiguration> {
        self.window
    }

    /// Sets the display name-independent Minecraft version (install-affecting
    /// and validated by [`Self::validate`]).
    pub fn set_minecraft_version(&mut self, version: impl Into<String>) {
        self.minecraft_version = version.into();
    }

    pub fn set_loader(&mut self, loader: LoaderConfiguration) {
        self.loader = loader;
    }

    pub fn set_memory_mib(&mut self, memory_mib: u32) {
        self.memory_mib = memory_mib;
    }

    pub fn set_additional_jvm_arguments(&mut self, text: impl Into<String>) {
        self.additional_jvm_arguments = text.into();
    }

    pub fn set_window(&mut self, window: Option<WindowConfiguration>) {
        self.window = window;
    }

    /// Validates the whole configuration. Every rule is a deliberate
    /// product decision: a valid configuration is always installable or
    /// launchable once its content exists.
    pub fn validate(&self) -> Result<(), InvalidInstanceConfiguration> {
        MinecraftVersionId::new(self.minecraft_version.trim())
            .map_err(InvalidInstanceConfiguration::MinecraftVersion)?;
        if self.minecraft_version.trim() != self.minecraft_version {
            return Err(InvalidInstanceConfiguration::MinecraftVersion(
                InvalidMinecraftVersion {
                    reason: format!(
                        "the configured Minecraft version must not have leading or trailing whitespace ('{}')",
                        self.minecraft_version
                    ),
                },
            ));
        }
        if self.loader.kind != LoaderKind::Fabric {
            return Err(InvalidInstanceConfiguration::UnsupportedLoaderKind);
        }
        if let LoaderPolicy::Pinned { version } = &self.loader.policy {
            if version.trim() != version || version.is_empty() {
                return Err(InvalidInstanceConfiguration::LoaderVersionInvalid);
            }
            crate::fabric::metadata::LoaderVersionId::new(version)
                .map_err(|_| InvalidInstanceConfiguration::LoaderVersionInvalid)?;
        }
        validate_memory_mib(self.memory_mib)?;
        parse_jvm_arguments(&self.additional_jvm_arguments)?;
        if let Some(window) = self.window {
            validate_window_dimension("width", window.width)?;
            validate_window_dimension("height", window.height)?;
        }
        Ok(())
    }

    /// Whether this configuration wants the same installed content as the
    /// given release pin — the install-affecting comparison. Memory, JVM
    /// arguments, window, and display name never participate.
    ///
    /// An `Automatic` loader policy matches whatever loader version is
    /// installed (the policy is a choice made at install time, and installed
    /// state never drifts); only a `Pinned` policy can disagree with it.
    pub fn matches_release_pin(
        &self,
        minecraft_version: &str,
        fabric_loader_version: &str,
    ) -> bool {
        if self.minecraft_version != minecraft_version {
            return false;
        }
        match &self.loader.policy {
            LoaderPolicy::Automatic => true,
            LoaderPolicy::Pinned { version } => version == fabric_loader_version,
        }
    }
}

impl LoaderConfiguration {
    pub fn fabric(policy: LoaderPolicy) -> Self {
        Self {
            kind: LoaderKind::Fabric,
            policy,
        }
    }

    /// Builds a loader configuration from its command-boundary parts; the
    /// only construction path outside deserialization and [`Self::fabric`].
    pub fn from_parts(kind: LoaderKind, policy: LoaderPolicy) -> Self {
        Self { kind, policy }
    }

    pub fn kind(&self) -> LoaderKind {
        self.kind
    }

    pub fn policy(&self) -> &LoaderPolicy {
        &self.policy
    }
}

impl LoaderPolicy {
    /// The concrete loader version this policy resolves to, given the
    /// newest-first candidate list the official Fabric Meta serves.
    ///
    /// `Automatic` picks the first stable entry (newest first ordering is
    /// Fabric Meta's own); `Pinned` requires its exact version to be present.
    pub fn resolve<'a>(&self, candidates: &'a [LoaderCandidate]) -> Option<&'a str> {
        match self {
            Self::Automatic => candidates
                .iter()
                .find(|candidate| candidate.stable)
                .map(|candidate| candidate.version.as_str()),
            Self::Pinned { version } => candidates
                .iter()
                .find(|candidate| candidate.version == *version)
                .map(|candidate| candidate.version.as_str()),
        }
    }
}

/// One candidate loader version for a Minecraft version, as listed by
/// official Fabric Meta (newest first, with the `stable` marker).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoaderCandidate {
    pub version: String,
    pub stable: bool,
}

impl WindowConfiguration {
    pub fn new(width: u16, height: u16) -> Self {
        Self { width, height }
    }

    pub fn width(&self) -> u16 {
        self.width
    }

    pub fn height(&self) -> u16 {
        self.height
    }
}

pub fn validate_memory_mib(memory_mib: u32) -> Result<(), InvalidInstanceConfiguration> {
    if !(MIN_MEMORY_MIB..=MAX_MEMORY_MIB).contains(&memory_mib) {
        return Err(InvalidInstanceConfiguration::MemoryOutOfRange {
            memory_mib,
            min: MIN_MEMORY_MIB,
            max: MAX_MEMORY_MIB,
        });
    }
    Ok(())
}

fn validate_window_dimension(
    name: &'static str,
    value: u16,
) -> Result<(), InvalidInstanceConfiguration> {
    if !(MIN_WINDOW_DIMENSION..=MAX_WINDOW_DIMENSION).contains(&value) {
        return Err(InvalidInstanceConfiguration::WindowDimensionOutOfRange {
            name,
            value,
            min: MIN_WINDOW_DIMENSION,
            max: MAX_WINDOW_DIMENSION,
        });
    }
    Ok(())
}

/// The authoritative heap argument for a memory configuration.
pub fn heap_argument(memory_mib: u32) -> String {
    format!("-Xmx{memory_mib}m")
}

/// Parses custom JVM argument text into an argument vector.
///
/// The quoting rules are documented on the module. Validation rejects
/// launcher-owned heap and classpath flags, oversized or control-character
/// arguments, and oversized vectors — the deterministic conflict policy that
/// keeps heap ownership unambiguous.
pub fn parse_jvm_arguments(text: &str) -> Result<Vec<String>, InvalidJvmArguments> {
    if text.len() > MAX_JVM_ARGUMENTS_TEXT_LENGTH {
        return Err(InvalidJvmArguments::TextTooLong {
            limit: MAX_JVM_ARGUMENTS_TEXT_LENGTH,
        });
    }
    if text.chars().any(char::is_control) {
        return Err(InvalidJvmArguments::ControlCharacter);
    }

    let mut arguments: Vec<String> = Vec::new();
    let mut current = String::new();
    let mut in_quotes = false;
    let mut current_has_content = false;
    let mut characters = text.chars().peekable();

    while let Some(character) = characters.next() {
        match character {
            '"' => {
                if in_quotes {
                    // A closing quote may be escaped by an odd run of
                    // backslashes; that run was already emitted as literal
                    // backslashes below. An empty quoted string is a real
                    // empty token.
                    in_quotes = false;
                    current_has_content = true;
                } else {
                    in_quotes = true;
                    current_has_content = true;
                }
            }
            '\\' => {
                // Count the run, then decide by what follows.
                let mut run = 1usize;
                while characters.peek() == Some(&'\\') {
                    characters.next();
                    run += 1;
                }
                match characters.peek() {
                    Some('"') => {
                        for _ in 0..run / 2 {
                            current.push('\\');
                        }
                        if run % 2 == 1 {
                            // Escaped quote: literal, quoting state unchanged.
                            characters.next();
                            current.push('"');
                        } else {
                            // Even run: backslashes literal, quote toggles.
                            characters.next();
                            in_quotes = !in_quotes;
                        }
                        current_has_content = true;
                    }
                    _ => {
                        for _ in 0..run {
                            current.push('\\');
                        }
                        current_has_content = true;
                    }
                }
            }
            ' ' | '\t' if !in_quotes => {
                if current_has_content || !current.is_empty() {
                    arguments.push(std::mem::take(&mut current));
                    current_has_content = false;
                }
            }
            other => {
                current.push(other);
                current_has_content = true;
            }
        }
    }

    if in_quotes {
        return Err(InvalidJvmArguments::UnterminatedQuote);
    }
    if current_has_content || !current.is_empty() {
        arguments.push(current);
    }

    if arguments.len() > MAX_JVM_ARGUMENT_COUNT {
        return Err(InvalidJvmArguments::TooManyArguments {
            limit: MAX_JVM_ARGUMENT_COUNT,
        });
    }
    for argument in &arguments {
        if argument.len() > MAX_JVM_ARGUMENT_LENGTH {
            return Err(InvalidJvmArguments::ArgumentTooLong {
                limit: MAX_JVM_ARGUMENT_LENGTH,
            });
        }
        if is_launcher_owned_flag(argument) {
            return Err(InvalidJvmArguments::LauncherOwnedFlag {
                argument: argument.to_owned(),
            });
        }
    }

    Ok(arguments)
}

/// The heap and classpath flags Aurora owns. A custom argument carrying one
/// is a conflict, reported — never silently dropped or silently overridden.
fn is_launcher_owned_flag(argument: &str) -> bool {
    const HEAP_PREFIXES: [&str; 7] = [
        "-Xmx",
        "-Xms",
        "-Xmn",
        "-XX:MaxHeapSize",
        "-XX:InitialHeapSize",
        "--max-heap-size",
        "--initial-heap-size",
    ];
    const CLASSPATH_FLAGS: [&str; 4] = ["-cp", "-classpath", "--class-path", "-jar"];

    HEAP_PREFIXES
        .iter()
        .any(|prefix| argument.starts_with(prefix))
        || CLASSPATH_FLAGS.contains(&argument)
}

/// A configuration that failed validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InvalidInstanceConfiguration {
    MinecraftVersion(InvalidMinecraftVersion),
    UnsupportedLoaderKind,
    LoaderVersionInvalid,
    MemoryOutOfRange {
        memory_mib: u32,
        min: u32,
        max: u32,
    },
    WindowDimensionOutOfRange {
        name: &'static str,
        value: u16,
        min: u16,
        max: u16,
    },
    JvmArguments(InvalidJvmArguments),
}

impl fmt::Display for InvalidInstanceConfiguration {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MinecraftVersion(error) => {
                write!(
                    formatter,
                    "the configured Minecraft version is invalid: {error}"
                )
            }
            Self::UnsupportedLoaderKind => write!(
                formatter,
                "the configured mod loader kind has no implemented installation and launch pipeline"
            ),
            Self::LoaderVersionInvalid => {
                write!(formatter, "the configured Fabric Loader version is invalid")
            }
            Self::MemoryOutOfRange {
                memory_mib,
                min,
                max,
            } => write!(
                formatter,
                "memory must be between {min} and {max} MiB, but is {memory_mib} MiB"
            ),
            Self::WindowDimensionOutOfRange {
                name,
                value,
                min,
                max,
            } => write!(
                formatter,
                "window {name} must be between {min} and {max} pixels, but is {value}"
            ),
            Self::JvmArguments(error) => write!(formatter, "{error}"),
        }
    }
}

impl std::error::Error for InvalidInstanceConfiguration {}

impl From<InvalidJvmArguments> for InvalidInstanceConfiguration {
    fn from(error: InvalidJvmArguments) -> Self {
        Self::JvmArguments(error)
    }
}

/// Custom JVM argument text that failed parsing or validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InvalidJvmArguments {
    UnterminatedQuote,
    ControlCharacter,
    TextTooLong { limit: usize },
    ArgumentTooLong { limit: usize },
    TooManyArguments { limit: usize },
    LauncherOwnedFlag { argument: String },
}

impl fmt::Display for InvalidJvmArguments {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnterminatedQuote => write!(
                formatter,
                "additional JVM arguments have an unterminated quote"
            ),
            Self::ControlCharacter => write!(
                formatter,
                "additional JVM arguments must not contain control characters"
            ),
            Self::TextTooLong { limit } => write!(
                formatter,
                "additional JVM arguments must be at most {limit} characters"
            ),
            Self::ArgumentTooLong { limit } => write!(
                formatter,
                "one additional JVM argument exceeds the {limit}-character limit"
            ),
            Self::TooManyArguments { limit } => write!(
                formatter,
                "additional JVM arguments must number at most {limit}"
            ),
            Self::LauncherOwnedFlag { argument } => write!(
                formatter,
                "additional JVM arguments cannot include '{argument}': Aurora owns the heap and classpath configuration"
            ),
        }
    }
}

impl std::error::Error for InvalidJvmArguments {}

#[cfg(test)]
mod tests {
    use super::*;

    fn configuration() -> InstanceConfiguration {
        InstanceConfiguration::for_minecraft_version("26.2")
    }

    #[test]
    fn defaults_are_safe_and_documented() {
        let config = InstanceConfiguration::for_minecraft_version("1.21.11");
        assert_eq!(config.memory_mib(), DEFAULT_MEMORY_MIB);
        assert_eq!(config.additional_jvm_arguments(), "");
        assert_eq!(config.window(), None);
        assert_eq!(config.loader().kind(), LoaderKind::Fabric);
        assert_eq!(config.loader().policy(), &LoaderPolicy::Automatic);
        assert!(config.validate().is_ok());
    }

    #[test]
    fn memory_boundaries_are_enforced() {
        assert!(validate_memory_mib(MIN_MEMORY_MIB).is_ok());
        assert!(validate_memory_mib(MAX_MEMORY_MIB).is_ok());
        for invalid in [0, 1, 511, 32_769, u32::MAX] {
            assert!(
                matches!(
                    validate_memory_mib(invalid),
                    Err(InvalidInstanceConfiguration::MemoryOutOfRange { memory_mib, .. }) if memory_mib == invalid
                ),
                "{invalid} MiB must be rejected"
            );
        }
    }

    #[test]
    fn heap_argument_is_exact_and_mib_addressed() {
        assert_eq!(heap_argument(2048), "-Xmx2048m");
        assert_eq!(heap_argument(512), "-Xmx512m");
        assert_eq!(heap_argument(32_768), "-Xmx32768m");
    }

    #[test]
    fn jvm_argument_parsing_preserves_boundaries_and_quotes() {
        assert_eq!(
            parse_jvm_arguments("-Dexample=value").unwrap(),
            vec!["-Dexample=value".to_owned()]
        );
        assert_eq!(
            parse_jvm_arguments("-Da=1 -Db=two words").unwrap(),
            vec!["-Da=1".to_owned(), "-Db=two".to_owned(), "words".to_owned()]
        );
        // Quoted spaces stay inside one argument.
        assert_eq!(
            parse_jvm_arguments(r#"-Dlabel="hello world" -Dx=y"#).unwrap(),
            vec!["-Dlabel=hello world".to_owned(), "-Dx=y".to_owned()]
        );
        // An explicit empty token.
        assert_eq!(
            parse_jvm_arguments(r#"-Da=1 "" -Db=2"#).unwrap(),
            vec!["-Da=1".to_owned(), String::new(), "-Db=2".to_owned()]
        );
        // Whitespace runs never produce empty tokens.
        assert_eq!(
            parse_jvm_arguments("  -Da=1   -Db=2  ").unwrap(),
            vec!["-Da=1".to_owned(), "-Db=2".to_owned()]
        );
        // Escaped quote inside quotes; a doubled backslash before a quote
        // yields one literal backslash and closes the quote. (A trailing
        // single `\"` would be a literal quote and leave the string
        // unterminated — malformed by the documented rules.)
        assert_eq!(
            parse_jvm_arguments(r#"-Dpath="C:\games\\" -Dq="say \"hi\"""#).unwrap(),
            vec![
                r#"-Dpath=C:\games\"#.to_owned(),
                r#"-Dq=say "hi""#.to_owned(),
            ]
        );
    }

    #[test]
    fn malformed_jvm_argument_text_fails_deliberately() {
        assert!(matches!(
            parse_jvm_arguments(r#"-Dbroken="unclosed"#),
            Err(InvalidJvmArguments::UnterminatedQuote)
        ));
        assert!(matches!(
            parse_jvm_arguments("-Dbad=\u{7}"),
            Err(InvalidJvmArguments::ControlCharacter)
        ));
        let too_many = vec!["-Dx=1"; MAX_JVM_ARGUMENT_COUNT + 1].join(" ");
        assert!(matches!(
            parse_jvm_arguments(&too_many),
            Err(InvalidJvmArguments::TooManyArguments { .. })
        ));
    }

    #[test]
    fn launcher_owned_flags_are_rejected_with_an_explanation() {
        for conflict in [
            "-Xmx12G",
            "-Xms2G",
            "-Xmn1G",
            "-XX:MaxHeapSize=4g",
            "-XX:InitialHeapSize=1g",
            "--max-heap-size=8g",
            "--initial-heap-size=8g",
            "-cp",
            "-classpath",
            "--class-path",
            "-jar",
        ] {
            let error =
                parse_jvm_arguments(conflict).expect_err("launcher-owned flags must be rejected");
            assert!(
                matches!(&error, InvalidJvmArguments::LauncherOwnedFlag { argument } if argument == conflict),
                "{conflict} must be a named conflict, got: {error}"
            );
            assert!(error.to_string().contains("Aurora owns"));
        }

        // Harmless ordinary properties pass.
        assert_eq!(
            parse_jvm_arguments("-Dexample=value -XX:+UseG1GC").unwrap(),
            vec!["-Dexample=value".to_owned(), "-XX:+UseG1GC".to_owned()]
        );
    }

    #[test]
    fn window_dimensions_are_bounded() {
        let mut config = configuration();
        config.set_window(Some(WindowConfiguration::new(854, 480)));
        assert!(config.validate().is_ok());
        config.set_window(Some(WindowConfiguration::new(
            MIN_WINDOW_DIMENSION,
            MAX_WINDOW_DIMENSION,
        )));
        assert!(config.validate().is_ok());
        config.set_window(Some(WindowConfiguration::new(99, 480)));
        assert!(config.validate().is_err());
        config.set_window(Some(WindowConfiguration::new(854, 7681)));
        assert!(config.validate().is_err());
    }

    #[test]
    fn minecraft_and_loader_versions_are_validated() {
        let mut config = configuration();
        assert!(config.validate().is_ok());

        config.set_minecraft_version("../evil");
        assert!(matches!(
            config.validate(),
            Err(InvalidInstanceConfiguration::MinecraftVersion(_))
        ));

        let mut padded = configuration();
        padded.set_minecraft_version(" 26.2 ");
        assert!(config_matches_minecraft_error(padded.validate()));

        let mut loader = configuration();
        loader.set_loader(LoaderConfiguration::fabric(LoaderPolicy::Pinned {
            version: " 0.19.5 ".to_owned(),
        }));
        assert!(matches!(
            loader.validate(),
            Err(InvalidInstanceConfiguration::LoaderVersionInvalid)
        ));

        let mut pinned = configuration();
        pinned.set_loader(LoaderConfiguration::fabric(LoaderPolicy::Pinned {
            version: "0.19.5".to_owned(),
        }));
        assert!(pinned.validate().is_ok());
    }

    fn config_matches_minecraft_error(result: Result<(), InvalidInstanceConfiguration>) -> bool {
        matches!(
            result,
            Err(InvalidInstanceConfiguration::MinecraftVersion(_))
        )
    }

    #[test]
    fn install_affecting_comparison_is_exact_and_policy_aware() {
        let mut config = configuration();
        assert!(config.matches_release_pin("26.2", "0.19.5"));

        // Automatic policy accepts whatever loader version is installed.
        assert!(config.matches_release_pin("26.2", "0.18.9"));
        // A different Minecraft version is stale.
        assert!(!config.matches_release_pin("1.21.11", "0.19.5"));

        config.set_loader(LoaderConfiguration::fabric(LoaderPolicy::Pinned {
            version: "0.19.5".to_owned(),
        }));
        assert!(config.matches_release_pin("26.2", "0.19.5"));
        assert!(!config.matches_release_pin("26.2", "0.19.4"));

        // Memory, JVM arguments, and window never affect the comparison.
        config.set_memory_mib(8192);
        config.set_additional_jvm_arguments("-Dx=y");
        config.set_window(Some(WindowConfiguration::new(1280, 720)));
        assert!(config.matches_release_pin("26.2", "0.19.5"));
    }

    #[test]
    fn loader_policy_resolution_follows_the_documented_rules() {
        let candidates = vec![
            LoaderCandidate {
                version: "0.19.5".to_owned(),
                stable: true,
            },
            LoaderCandidate {
                version: "0.19.4".to_owned(),
                stable: false,
            },
            LoaderCandidate {
                version: "0.19.3".to_owned(),
                stable: true,
            },
        ];

        // Automatic: the first (newest) stable entry.
        assert_eq!(LoaderPolicy::Automatic.resolve(&candidates), Some("0.19.5"));
        // Pinned: the exact version, stable or not.
        assert_eq!(
            LoaderPolicy::Pinned {
                version: "0.19.4".to_owned()
            }
            .resolve(&candidates),
            Some("0.19.4")
        );
        // A pinned version absent from the list does not resolve.
        assert_eq!(
            LoaderPolicy::Pinned {
                version: "0.99.0".to_owned()
            }
            .resolve(&candidates),
            None
        );
        // No stable loader at all: automatic fails honestly.
        let unstable_only = vec![LoaderCandidate {
            version: "0.19.4".to_owned(),
            stable: false,
        }];
        assert_eq!(LoaderPolicy::Automatic.resolve(&unstable_only), None);
    }

    #[test]
    fn configuration_round_trips_through_camel_case_json() {
        let mut config = configuration();
        config.set_memory_mib(4096);
        config.set_additional_jvm_arguments(r#"-Dexample="a b""#);
        config.set_window(Some(WindowConfiguration::new(1280, 720)));
        config.set_loader(LoaderConfiguration::fabric(LoaderPolicy::Pinned {
            version: "0.19.5".to_owned(),
        }));

        let json = serde_json::to_string_pretty(&config).unwrap();
        assert!(json.contains("\"minecraftVersion\": \"26.2\""));
        assert!(json.contains("\"memoryMib\": 4096"));
        assert!(json.contains("\"additionalJvmArguments\""));
        assert!(json.contains("\"width\": 1280"));
        assert!(json.contains("\"type\": \"pinned\""));
        assert_eq!(
            serde_json::from_str::<InstanceConfiguration>(&json).unwrap(),
            config
        );
    }

    #[test]
    fn migrated_configurations_preserve_the_pin_and_default_the_rest() {
        let migrated = InstanceConfiguration::migrated_from_release_pin("1.21.11", "0.19.5");
        assert_eq!(migrated.minecraft_version(), "1.21.11");
        assert_eq!(
            migrated.loader().policy(),
            &LoaderPolicy::Pinned {
                version: "0.19.5".to_owned()
            }
        );
        assert_eq!(migrated.memory_mib(), DEFAULT_MEMORY_MIB);
        assert_eq!(migrated.additional_jvm_arguments(), "");
        assert_eq!(migrated.window(), None);
        assert!(migrated.validate().is_ok());
    }
}
