//! Deterministic invariants over Aurora's canonical icon artwork and the
//! generated external application identity.
//!
//! Aurora has two canonical asset roles (ARCHITECTURE.md):
//!
//! - the internal transparent white mark (`static/aurora-icon.png`) — the
//!   byte-for-byte developer artwork; its integrity is pinned by hash;
//! - the external application icon (`static/aurora-app-icon.png` plus the
//!   `src-tauri/icons/` derivatives) — deterministically generated by
//!   `tools/generate_external_icon.py` from the internal mark.
//!
//! These tests prove the shipped assets still satisfy the design contract:
//! dimensions, transparent corners, gradient direction, neutral palette,
//! and the Windows ICO frame inventory and ordering — including the
//! load-bearing rule that ICO entry[0] is the 40x40 frame tauri-codegen
//! rasterizes the runtime window icon from (the afdc609 lesson).

use std::path::Path;

/// Repository root (the manifest dir is `src-tauri`).
fn repo_root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap()
}

const INTERNAL_MARK_SHA256: &str =
    "faba1af24b964cfd085505c63e9e43d7abedebd70d70794e841a3251d0fa5a19";

/// The exact ICO frame sizes the Windows pipeline requires, in the exact
/// directory order that preserves entry[0] = 40x40.
const ICO_FRAME_ORDER: [u32; 9] = [40, 16, 20, 24, 32, 48, 64, 128, 256];

/// Design parameters of the external master (must match the generator).
const GRADIENT_TOP: [u8; 3] = [38, 39, 42];
const GRADIENT_BOTTOM: [u8; 3] = [5, 5, 6];

fn sha256_file(path: &Path) -> String {
    use sha2::{Digest, Sha256};

    let bytes = std::fs::read(path).expect("asset file is readable");
    let digest = Sha256::digest(&bytes);
    digest.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn decode_rgba(path: &Path) -> (u32, u32, Vec<u8>) {
    let bytes = std::fs::read(path).expect("asset file is readable");
    let decoder = png::Decoder::new(std::io::Cursor::new(&bytes));
    let mut reader = decoder.read_info().expect("png info");
    let mut buffer = vec![0; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buffer).expect("png pixels");
    assert_eq!(
        info.color_type,
        png::ColorType::Rgba,
        "{} must be RGBA",
        path.display()
    );
    (info.width, info.height, buffer)
}

#[test]
fn internal_mark_is_byte_identical_to_the_developer_artwork() {
    let path = repo_root().join("static").join("aurora-icon.png");
    assert_eq!(sha256_file(&path), INTERNAL_MARK_SHA256);
}

#[test]
fn external_master_has_the_documented_canvas_and_alpha() {
    let path = repo_root().join("static").join("aurora-app-icon.png");
    assert!(
        path.exists(),
        "the external canonical master must be tracked"
    );
    let (width, height, pixels) = decode_rgba(&path);
    assert_eq!((width, height), (1024, 1024));

    // The canvas outside the rounded square is fully transparent.
    let corner = |x: u32, y: u32| {
        let offset = ((y * width + x) * 4) as usize;
        assert_eq!(
            &pixels[offset..offset + 4],
            &[0, 0, 0, 0],
            "corner ({x},{y})"
        );
    };
    corner(0, 0);
    corner(width - 1, 0);
    corner(0, height - 1);
    corner(width - 1, height - 1);
    corner(8, 8);
    corner(width - 9, height - 9);

    // The square's body is opaque.
    let offset = ((height / 2 * width + width / 2) * 4) as usize;
    assert_eq!(pixels[offset + 3], 255);
}

#[test]
fn external_master_gradient_runs_light_at_top_dark_at_bottom() {
    let path = repo_root().join("static").join("aurora-app-icon.png");
    let (width, height, pixels) = decode_rgba(&path);

    let sample = |x: u32, y: u32| -> [u8; 3] {
        let offset = ((y * width + x) * 4) as usize;
        [pixels[offset], pixels[offset + 1], pixels[offset + 2]]
    };

    // Sample near the left edge inside the rounded square, away from the
    // mark: rows from the upper body to the lower body must darken
    // monotonically.
    let top = sample(width / 8, height / 4);
    let middle = sample(width / 8, height / 2);
    let bottom = sample(width / 8, height * 3 / 4);

    let luminance = |rgb: [u8; 3]| i32::from(rgb[0]) + i32::from(rgb[1]) + i32::from(rgb[2]);
    assert!(
        luminance(top) > luminance(middle),
        "gradient must run lighter at the top: {top:?} vs {middle:?}"
    );
    assert!(
        luminance(middle) > luminance(bottom),
        "gradient must darken toward the bottom: {middle:?} vs {bottom:?}"
    );

    // The gradient is the documented sRGB lerp between the two stops, and
    // it is purely vertical: every sampled background row matches its
    // interpolated stop, and a row has the same value on both sides of the
    // mark. The sampled columns sit inside the rounded square for the whole
    // sampled range and outside the mark's horizontal extent.
    let expected_at = |y: u32| -> [u8; 3] {
        let t = f64::from(y) / f64::from(height - 1);
        let mut stop = [0u8; 3];
        for channel in 0..3 {
            let value = f64::from(GRADIENT_TOP[channel])
                + (f64::from(GRADIENT_BOTTOM[channel]) - f64::from(GRADIENT_TOP[channel])) * t;
            stop[channel] = value.round() as u8;
        }
        stop
    };
    for y in (32..height - 32).step_by(97) {
        let expected = expected_at(y);
        for x in [160, 864] {
            let offset = ((y * width + x) * 4) as usize;
            assert_eq!(
                pixels[offset + 3],
                255,
                "sample ({x},{y}) inside the square"
            );
            let actual = [pixels[offset], pixels[offset + 1], pixels[offset + 2]];
            for channel in 0..3 {
                assert!(
                    actual[channel].abs_diff(expected[channel]) <= 2,
                    "row {y} column {x} channel {channel}: expected ~{expected:?}, found {actual:?}"
                );
            }
        }
    }
}

#[test]
fn external_master_stays_neutral_and_carries_the_white_mark() {
    let path = repo_root().join("static").join("aurora-app-icon.png");
    let (width, height, pixels) = decode_rgba(&path);

    let expected_at = |y: u32| -> [u8; 3] {
        let t = f64::from(y) / f64::from(height - 1);
        let mut stop = [0u8; 3];
        for channel in 0..3 {
            let value = f64::from(GRADIENT_TOP[channel])
                + (f64::from(GRADIENT_BOTTOM[channel]) - f64::from(GRADIENT_TOP[channel])) * t;
            stop[channel] = value.round() as u8;
        }
        stop
    };

    let mut background_pixels = 0;
    let mut bright_pixels = 0;
    let mut max_spread = 0u8;
    for y in (0..height).step_by(4) {
        let expected = expected_at(y);
        for x in (0..width).step_by(4) {
            let offset = ((y * width + x) * 4) as usize;
            let alpha = pixels[offset + 3];
            if alpha != 255 {
                continue;
            }
            let (r, g, b) = (pixels[offset], pixels[offset + 1], pixels[offset + 2]);
            // Only unambiguous gradient body pixels count for the neutrality
            // check: pixels tightly matching the row's interpolated stop.
            // Anything else is mark coverage, mask edge, or resampling
            // ringing near the mark, not background.
            let near_stop = r.abs_diff(expected[0]) <= 6
                && g.abs_diff(expected[1]) <= 6
                && b.abs_diff(expected[2]) <= 6;
            if near_stop {
                background_pixels += 1;
                let spread = r.max(g).max(b) - r.min(g).min(b);
                max_spread = max_spread.max(spread);
            } else if r.min(g).min(b) > 200 {
                bright_pixels += 1;
            }
        }
    }

    // Neutral dark background: no accidental blue/purple cast. The stops
    // themselves carry a spread of 4 (38,39,42), so the bound is the stops'
    // own spread — any tint beyond it would mean a colored gradient.
    assert!(
        max_spread <= 4,
        "background must stay neutral; spread {max_spread}"
    );
    assert!(background_pixels > 20_000, "expected a dark gradient body");
    // The white mark is present.
    assert!(bright_pixels > 2_000, "expected the white Aurora mark");
}

#[test]
fn windows_ico_has_the_exact_frames_in_the_load_bearing_order() {
    let path = repo_root().join("src-tauri").join("icons").join("icon.ico");
    let data = std::fs::read(&path).expect("icon.ico is readable");

    assert!(data.len() >= 6);
    assert_eq!(&data[0..2], &[0, 0], "reserved must be zero");
    assert_eq!(&data[2..4], &[1, 0], "type must be icon");
    let count = u16::from_le_bytes([data[4], data[5]]) as usize;
    assert_eq!(count, ICO_FRAME_ORDER.len());

    let mut offset = 6;
    for (index, expected_size) in ICO_FRAME_ORDER.into_iter().enumerate() {
        let entry = &data[offset..offset + 16];
        let width = entry[0];
        let height = entry[1];
        let planes = u16::from_le_bytes([entry[4], entry[5]]);
        let bpp = u16::from_le_bytes([entry[6], entry[7]]);
        let size = u32::from_le_bytes([entry[8], entry[9], entry[10], entry[11]]);
        let frame_offset = u32::from_le_bytes([entry[12], entry[13], entry[14], entry[15]]);

        let declared = if width == 0 { 256 } else { u32::from(width) };
        assert_eq!(declared, expected_size, "entry[{index}] width");
        let declared_height = if height == 0 { 256 } else { u32::from(height) };
        assert_eq!(declared_height, expected_size, "entry[{index}] height");
        assert_eq!(planes, 1, "entry[{index}] color planes");
        assert_eq!(bpp, 32, "entry[{index}] must be 32bpp");
        assert!(size > 0, "entry[{index}] carries pixel data");
        assert!(frame_offset as usize + size as usize <= data.len());
        offset += 16;
    }

    // The load-bearing rule: tauri-codegen rasterizes the runtime window
    // icon from ICO entry[0]; it must be the 40x40 frame (afdc609).
    assert_eq!(ICO_FRAME_ORDER[0], 40);
}

#[test]
fn icon_derivatives_exist_with_the_documented_dimensions() {
    let icons = repo_root().join("src-tauri").join("icons");
    let expected = [
        ("icon.png", 512),
        ("32x32.png", 32),
        ("128x128.png", 128),
        ("128x128@2x.png", 256),
        ("Square30x30Logo.png", 30),
        ("Square44x44Logo.png", 44),
        ("Square71x71Logo.png", 71),
        ("Square89x89Logo.png", 89),
        ("Square107x107Logo.png", 107),
        ("Square142x142Logo.png", 142),
        ("Square150x150Logo.png", 150),
        ("Square284x284Logo.png", 284),
        ("Square310x310Logo.png", 310),
        ("StoreLogo.png", 50),
    ];
    for (name, size) in expected {
        let path = icons.join(name);
        let (width, height, _) = decode_rgba(&path);
        assert_eq!((width, height), (size, size), "{name} dimensions");
    }

    // The favicon is the external identity at its browser size.
    let (width, height, _) = decode_rgba(&repo_root().join("static").join("favicon.png"));
    assert_eq!((width, height), (128, 128));

    // The ICNS container carries the modern PNG chunk set.
    let icns = std::fs::read(icons.join("icon.icns")).expect("icon.icns is readable");
    assert_eq!(&icns[0..4], b"icns");
    let mut offset = 8;
    let mut seen = Vec::new();
    while offset + 8 <= icns.len() {
        let chunk_len = u32::from_be_bytes([
            icns[offset + 4],
            icns[offset + 5],
            icns[offset + 6],
            icns[offset + 7],
        ]) as usize;
        seen.push(icns[offset..offset + 4].to_vec());
        offset += chunk_len;
    }
    for expected in [b"ic07", b"ic08", b"ic09", b"ic10"] {
        assert!(
            seen.iter().any(|chunk| chunk == expected),
            "icns must contain {expected:?} (found {seen:?})"
        );
    }
}
